In [36]:
#import the pandas library to read a CSV file
import pandas as pd
#import the numpy library to create a numpy array
import numpy as np

In [37]:
data = pd.read_csv('C:/Users/pc/Downloads/final_dataset_act_phy.csv')

In [38]:
data

,time,label,ax,ay,az,gx,gy,gz,user,user_id,file_name,gender,age_yrs,height_cm,weight_kg
0,2023-05-24 05:35:53.608,Wa,-0.670377,3.270479,8.746018,-0.151217,0.560371,1.868568,1,user1,user1.csv,F,26.0,152.0,42.0
1,2023-05-24 05:35:53.674,Wa,-0.660800,3.234567,8.693346,-0.130300,0.451787,1.822870,1,user1,user1.csv,F,26.0,152.0,42.0
2,2023-05-24 05:35:53.719,Wa,-0.265756,3.040636,8.350976,-0.047963,0.359858,1.698565,1,user1,user1.csv,F,26.0,152.0,42.0
3,2023-05-24 05:35:53.759,Wa,0.122104,2.983175,8.288726,0.077674,0.239417,1.575726,1,user1,user1.csv,F,26.0,152.0,42.0
4,2023-05-24 05:35:53.804,Wa,0.507571,3.471592,8.688558,0.215835,0.410086,1.353096,1,user1,user1.csv,F,26.0,152.0,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399053,1970-01-20 10:57:00.030710776,Wr,9.428367,2.913743,2.188300,-0.055557,-0.302435,0.008793,33,user33,NaN,NaN,NaN,NaN,NaN
399054,1970-01-20 10:57:00.030762669,Wr,9.610326,2.997540,2.020706,-0.051427,-0.331479,0.015988,33,user33,NaN,NaN,NaN,NaN,NaN
399055,1970-01-20 10:57:00.030814856,Wr,9.397242,3.090914,2.042254,-0.059021,-0.219965,-0.023982,33,user33,NaN,NaN,NaN,NaN,NaN
399056,1970-01-20 10:57:00.030865004,Wr,9.761160,2.992752,1.924938,-0.006928,-0.189988,-0.037438,33,user33,NaN,NaN,NaN,NaN,NaN
399057,1970-01-20 10:57:00.030915443,Wr,9.308656,3.110068,2.106898,0.021317,-0.129501,-0.038637,33,user33,NaN,NaN,NaN,NaN,NaN

In [39]:
data.drop(['user','user_id','file_name'], axis =1, inplace=True)

In [40]:
data

,time,label,ax,ay,az,gx,gy,gz,gender,age_yrs,height_cm,weight_kg
0,2023-05-24 05:35:53.608,Wa,-0.670377,3.270479,8.746018,-0.151217,0.560371,1.868568,F,26.0,152.0,42.0
1,2023-05-24 05:35:53.674,Wa,-0.660800,3.234567,8.693346,-0.130300,0.451787,1.822870,F,26.0,152.0,42.0
2,2023-05-24 05:35:53.719,Wa,-0.265756,3.040636,8.350976,-0.047963,0.359858,1.698565,F,26.0,152.0,42.0
3,2023-05-24 05:35:53.759,Wa,0.122104,2.983175,8.288726,0.077674,0.239417,1.575726,F,26.0,152.0,42.0
4,2023-05-24 05:35:53.804,Wa,0.507571,3.471592,8.688558,0.215835,0.410086,1.353096,F,26.0,152.0,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...
399053,1970-01-20 10:57:00.030710776,Wr,9.428367,2.913743,2.188300,-0.055557,-0.302435,0.008793,NaN,NaN,NaN,NaN
399054,1970-01-20 10:57:00.030762669,Wr,9.610326,2.997540,2.020706,-0.051427,-0.331479,0.015988,NaN,NaN,NaN,NaN
399055,1970-01-20 10:57:00.030814856,Wr,9.397242,3.090914,2.042254,-0.059021,-0.219965,-0.023982,NaN,NaN,NaN,NaN
399056,1970-01-20 10:57:00.030865004,Wr,9.761160,2.992752,1.924938,-0.006928,-0.189988,-0.037438,NaN,NaN,NaN,NaN
399057,1970-01-20 10:57:00.030915443,Wr,9.308656,3.110068,2.106898,0.021317,-0.129501,-0.038637,NaN,NaN,NaN,NaN

In [41]:
# Check for NaN (Not a Number) values in your DataFrame
data.isnull().sum()

time            0
label           0
ax              0
ay              0
az              0
gx              0
gy              0
gz              0
gender       3714
age_yrs      3714
height_cm    3714
weight_kg    3714
dtype: int64

In [42]:
# Handle NaN values (Drop rows with NaN)
data.dropna(inplace=True)

In [43]:
data

,time,label,ax,ay,az,gx,gy,gz,gender,age_yrs,height_cm,weight_kg
0,2023-05-24 05:35:53.608,Wa,-0.670377,3.270479,8.746018,-0.151217,0.560371,1.868568,F,26.0,152.0,42.0
1,2023-05-24 05:35:53.674,Wa,-0.660800,3.234567,8.693346,-0.130300,0.451787,1.822870,F,26.0,152.0,42.0
2,2023-05-24 05:35:53.719,Wa,-0.265756,3.040636,8.350976,-0.047963,0.359858,1.698565,F,26.0,152.0,42.0
3,2023-05-24 05:35:53.759,Wa,0.122104,2.983175,8.288726,0.077674,0.239417,1.575726,F,26.0,152.0,42.0
4,2023-05-24 05:35:53.804,Wa,0.507571,3.471592,8.688558,0.215835,0.410086,1.353096,F,26.0,152.0,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...
395339,1970-01-20 10:55:34.901350527,T,6.797139,3.414132,8.583213,-0.339074,-0.168937,0.031176,F,77.0,154.0,45.0
395340,1970-01-20 10:55:34.901401618,T,5.513846,3.263297,6.703765,-0.228758,-0.008394,0.014922,F,77.0,154.0,45.0
395341,1970-01-20 10:55:34.901454241,T,6.193800,3.560178,5.856217,0.057156,0.051560,0.056090,F,77.0,154.0,45.0
395342,1970-01-20 10:55:34.901505628,T,6.718130,3.512294,7.817069,0.336542,0.080605,-0.005995,F,77.0,154.0,45.0
395343,1970-01-20 10:55:34.901557242,T,6.804321,4.031836,9.801862,-0.027446,-0.019452,0.053825,F,77.0,154.0,45.0

In [44]:
data['gender'] = data['gender'].map({'M': 1, 'F': 0})

In [45]:
# Extract only the time part (HH:MM:SS.sss) from full timestamps
data["time"] = data["time"].astype(str).str.split().str[-1]  # Get the time portion

# Convert time format HH:MM:SS.sss to total seconds
def time_to_seconds(time_str):
    try:
        h, m, s = map(float, time_str.split(":"))
        return h * 3600 + m * 60 + s
    except ValueError:
        return None  # Handle unexpected formats

# Apply the conversion
data["time"] = data["time"].apply(time_to_seconds)

# Drop any rows with invalid time values
data = data.dropna(subset=["time"])

In [46]:
data

,time,label,ax,ay,az,gx,gy,gz,gender,age_yrs,height_cm,weight_kg
0,20153.608000,Wa,-0.670377,3.270479,8.746018,-0.151217,0.560371,1.868568,0,26.0,152.0,42.0
1,20153.674000,Wa,-0.660800,3.234567,8.693346,-0.130300,0.451787,1.822870,0,26.0,152.0,42.0
2,20153.719000,Wa,-0.265756,3.040636,8.350976,-0.047963,0.359858,1.698565,0,26.0,152.0,42.0
3,20153.759000,Wa,0.122104,2.983175,8.288726,0.077674,0.239417,1.575726,0,26.0,152.0,42.0
4,20153.804000,Wa,0.507571,3.471592,8.688558,0.215835,0.410086,1.353096,0,26.0,152.0,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...
395339,39334.901351,T,6.797139,3.414132,8.583213,-0.339074,-0.168937,0.031176,0,77.0,154.0,45.0
395340,39334.901402,T,5.513846,3.263297,6.703765,-0.228758,-0.008394,0.014922,0,77.0,154.0,45.0
395341,39334.901454,T,6.193800,3.560178,5.856217,0.057156,0.051560,0.056090,0,77.0,154.0,45.0
395342,39334.901506,T,6.718130,3.512294,7.817069,0.336542,0.080605,-0.005995,0,77.0,154.0,45.0
395343,39334.901557,T,6.804321,4.031836,9.801862,-0.027446,-0.019452,0.053825,0,77.0,154.0,45.0

In [47]:
data['label'] = data['label'].map({'Wa': 0, 'J': 1,'C':2})

In [48]:
data

,time,label,ax,ay,az,gx,gy,gz,gender,age_yrs,height_cm,weight_kg
0,20153.608000,0.0,-0.670377,3.270479,8.746018,-0.151217,0.560371,1.868568,0,26.0,152.0,42.0
1,20153.674000,0.0,-0.660800,3.234567,8.693346,-0.130300,0.451787,1.822870,0,26.0,152.0,42.0
2,20153.719000,0.0,-0.265756,3.040636,8.350976,-0.047963,0.359858,1.698565,0,26.0,152.0,42.0
3,20153.759000,0.0,0.122104,2.983175,8.288726,0.077674,0.239417,1.575726,0,26.0,152.0,42.0
4,20153.804000,0.0,0.507571,3.471592,8.688558,0.215835,0.410086,1.353096,0,26.0,152.0,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...
395339,39334.901351,NaN,6.797139,3.414132,8.583213,-0.339074,-0.168937,0.031176,0,77.0,154.0,45.0
395340,39334.901402,NaN,5.513846,3.263297,6.703765,-0.228758,-0.008394,0.014922,0,77.0,154.0,45.0
395341,39334.901454,NaN,6.193800,3.560178,5.856217,0.057156,0.051560,0.056090,0,77.0,154.0,45.0
395342,39334.901506,NaN,6.718130,3.512294,7.817069,0.336542,0.080605,-0.005995,0,77.0,154.0,45.0
395343,39334.901557,NaN,6.804321,4.031836,9.801862,-0.027446,-0.019452,0.053825,0,77.0,154.0,45.0

In [49]:
# Check for NaN (Not a Number) values in your DataFrame
data.isnull().sum()

time              0
label        201592
ax                0
ay                0
az                0
gx                0
gy                0
gz                0
gender            0
age_yrs           0
height_cm         0
weight_kg         0
dtype: int64

In [50]:
# Handle NaN values (Drop rows with NaN)
data.dropna(inplace=True)

In [51]:
data

,time,label,ax,ay,az,gx,gy,gz,gender,age_yrs,height_cm,weight_kg
0,20153.608000,0.0,-0.670377,3.270479,8.746018,-0.151217,0.560371,1.868568,0,26.0,152.0,42.0
1,20153.674000,0.0,-0.660800,3.234567,8.693346,-0.130300,0.451787,1.822870,0,26.0,152.0,42.0
2,20153.719000,0.0,-0.265756,3.040636,8.350976,-0.047963,0.359858,1.698565,0,26.0,152.0,42.0
3,20153.759000,0.0,0.122104,2.983175,8.288726,0.077674,0.239417,1.575726,0,26.0,152.0,42.0
4,20153.804000,0.0,0.507571,3.471592,8.688558,0.215835,0.410086,1.353096,0,26.0,152.0,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...
389317,39334.053434,0.0,2.925714,-9.430760,1.240196,0.003198,-0.065949,0.001332,0,77.0,154.0,45.0
389318,39334.053488,0.0,3.014300,-9.497798,1.223437,-0.003730,-0.045032,0.009326,0,77.0,154.0,45.0
389319,39334.053538,0.0,2.937685,-9.447520,1.271321,-0.015055,-0.035173,0.016521,0,77.0,154.0,45.0
389320,39334.053591,0.0,2.908955,-9.392453,1.288081,-0.013323,-0.067948,0.000400,0,77.0,154.0,45.0
389321,39334.053643,0.0,2.954445,-9.454702,1.288081,-0.009593,-0.065949,0.001066,0,77.0,154.0,45.0

In [52]:
data.to_csv('df.csv', index=False)

In [53]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 193752 entries, 0 to 389321
Data columns (total 12 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   time       193752 non-null  float64
 1   label      193752 non-null  float64
 2   ax         193752 non-null  float64
 3   ay         193752 non-null  float64
 4   az         193752 non-null  float64
 5   gx         193752 non-null  float64
 6   gy         193752 non-null  float64
 7   gz         193752 non-null  float64
 8   gender     193752 non-null  int64
 9   age_yrs    193752 non-null  float64
 10  height_cm  193752 non-null  float64
 11  weight_kg  193752 non-null  float64
dtypes: float64(11), int64(1)
memory usage: 19.2 MB

In [54]:
data.describe()

,time,label,ax,ay,az,gx,gy,gz,gender,age_yrs,height_cm,weight_kg
count,193752.000000,193752.000000,193752.000000,193752.000000,193752.000000,193752.000000,193752.000000,193752.000000,193752.000000,193752.000000,193752.00000,193752.000000
mean,34115.765925,0.599132,4.342854,2.054409,2.773343,-0.005207,-0.088306,-0.006111,0.787775,30.138935,167.17991,68.905379
std,7618.084613,0.683179,5.781165,8.018187,3.837991,1.179872,1.295824,1.509745,0.408884,8.544422,11.92691,15.818074
min,20153.608000,0.000000,-19.613300,-19.613300,-19.613300,-4.365721,-4.365721,-4.365721,0.000000,6.000000,110.00000,20.000000
25%,30108.324742,0.000000,1.082179,-4.953603,0.682347,-0.541319,-0.710256,-0.763815,1.000000,27.000000,158.00000,55.000000
50%,30141.885398,0.000000,2.559402,3.740940,2.377442,-0.027312,-0.075009,-0.015721,1.000000,30.000000,170.00000,70.000000
75%,38987.780568,1.000000,5.638345,8.836999,4.455609,0.504680,0.558639,0.758752,1.000000,31.000000,175.00000,80.000000
max,58411.600000,2.000000,19.612701,30.000000,30.000000,4.365588,12.536040,7.812351,1.000000,77.000000,182.00000,91.000000

In [55]:
#create two variables, X (features) and y (target)
X = data[['gender','age_yrs','time','height_cm','weight_kg','ax','ay','az','gx','gy','gz']]
y = data['label']

In [56]:
#split your data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [57]:
#create a linear regression model using the LinearRegression class
from sklearn.linear_model import LinearRegression
model=LinearRegression()
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
model2=GradientBoostingRegressor()
model3=RandomForestRegressor()

In [58]:
#train your linear regression model on your training data
model.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)

RandomForestRegressor()

In [59]:
#make predictions on your test data
y_pred = model.predict(X_test)
y_pred2 = model2.predict(X_test)
y_pred3 = model3.predict(X_test)

In [60]:
#compare these predictions (y_pred) to the actual values (y_test)
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
print(f"Root Mean Squared Error: {rmse}")
print(f"R-squared: {r2}")

Mean Squared Error: 0.32932974633650924
Root Mean Squared Error: 0.5738725871972883
R-squared: 0.2898666903857724

In [61]:
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred2)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred2)

print(f"Mean Squared Error: {mse}")
print(f"Root Mean Squared Error: {rmse}")
print(f"R-squared: {r2}")

Mean Squared Error: 0.04617263190222672
Root Mean Squared Error: 0.21487817921377386
R-squared: 0.9004380130520484

In [62]:
#best model
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred3)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred3)

print(f"Mean Squared Error: {mse}")
print(f"Root Mean Squared Error: {rmse}")
print(f"R-squared: {r2}")

Mean Squared Error: 0.010604495367861474
Root Mean Squared Error: 0.10297813053197982
R-squared: 0.97713354024002

In [63]:
data

,time,label,ax,ay,az,gx,gy,gz,gender,age_yrs,height_cm,weight_kg
0,20153.608000,0.0,-0.670377,3.270479,8.746018,-0.151217,0.560371,1.868568,0,26.0,152.0,42.0
1,20153.674000,0.0,-0.660800,3.234567,8.693346,-0.130300,0.451787,1.822870,0,26.0,152.0,42.0
2,20153.719000,0.0,-0.265756,3.040636,8.350976,-0.047963,0.359858,1.698565,0,26.0,152.0,42.0
3,20153.759000,0.0,0.122104,2.983175,8.288726,0.077674,0.239417,1.575726,0,26.0,152.0,42.0
4,20153.804000,0.0,0.507571,3.471592,8.688558,0.215835,0.410086,1.353096,0,26.0,152.0,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...
389317,39334.053434,0.0,2.925714,-9.430760,1.240196,0.003198,-0.065949,0.001332,0,77.0,154.0,45.0
389318,39334.053488,0.0,3.014300,-9.497798,1.223437,-0.003730,-0.045032,0.009326,0,77.0,154.0,45.0
389319,39334.053538,0.0,2.937685,-9.447520,1.271321,-0.015055,-0.035173,0.016521,0,77.0,154.0,45.0
389320,39334.053591,0.0,2.908955,-9.392453,1.288081,-0.013323,-0.067948,0.000400,0,77.0,154.0,45.0
389321,39334.053643,0.0,2.954445,-9.454702,1.288081,-0.009593,-0.065949,0.001066,0,77.0,154.0,45.0

In [64]:
new_data = {
    'gender': 0, 
    'age_yrs': 26.0, 
    'time': 20153.759000,
    'height_cm': 152.0, 
    'weight_kg': 42.0,
    'ax': 0.122104,
    'ay': 2.983175,
    'az': 8.288726,
    'gx': 0.077674,
    'gy': 0.239417, 
    'gz': 1.575726, 
}

# Creating a DataFrame from the new data (assuming you have pandas imported as pd)
new_df = pd.DataFrame([new_data])

# Making predictions using the pre-trained model
predicted_value = model.predict(new_df)

# S'assurer que la prédiction est bien un float
exact_prediction = float(predicted_value.flatten()[0])  # Convertir proprement en float

# Afficher la valeur prédite exacte
print(f"Predicted value: {exact_prediction}")

# Arrondir pour faire correspondre aux catégories
rounded_prediction = round(exact_prediction)

# Convertir la prédiction en activité physique
activity_mapping = {0: "Walking", 1: "Jogging", 2: "Cycling"}
predicted_activity = activity_mapping.get(rounded_prediction, "Unknown")

# Afficher l'activité prédite
print(f"Predicted activity: {predicted_activity}")

Predicted value: 0.716602948297234
Predicted activity: Jogging

In [65]:
new_data = {
    'gender': 0, 
    'age_yrs': 26.0, 
    'time': 20153.759000,
    'height_cm': 152.0, 
    'weight_kg': 42.0,
    'ax': 0.122104,
    'ay': 2.983175,
    'az': 8.288726,
    'gx': 0.077674,
    'gy': 0.239417, 
    'gz': 1.575726, 
}

# Creating a DataFrame from the new data (assuming you have pandas imported as pd)
new_df = pd.DataFrame([new_data])

# Making predictions using the pre-trained model
predicted_value = model2.predict(new_df)

# S'assurer que la prédiction est bien un float
exact_prediction = float(predicted_value.flatten()[0])  # Convertir proprement en float

# Afficher la valeur prédite exacte
print(f"Predicted value: {exact_prediction}")

# Arrondir pour faire correspondre aux catégories
rounded_prediction = round(exact_prediction)

# Convertir la prédiction en activité physique
activity_mapping = {0: "Walking", 1: "Jogging", 2: "Cycling"}
predicted_activity = activity_mapping.get(rounded_prediction, "Unknown")

# Afficher l'activité prédite
print(f"Predicted activity: {predicted_activity}")

Predicted value: 0.4620428011035654
Predicted activity: Walking

In [66]:
new_data = {
    'gender': 0, 
    'age_yrs': 26.0, 
    'time': 20306.902,
    'height_cm': 152.0, 
    'weight_kg': 42.0,
    'ax': 19.612701,
    'ay': -3.2944214,
    'az': -2.0590134,
    'gx': -2.4357336,
    'gy': -1.5075115, 
    'gz': -4.2316904, 
}

# Creating a DataFrame from the new data (assuming you have pandas imported as pd)
new_df = pd.DataFrame([new_data])

# Making predictions using the pre-trained model
predicted_value = model3.predict(new_df)

# S'assurer que la prédiction est bien un float
exact_prediction = float(predicted_value.flatten()[0])  # Convertir proprement en float

# Afficher la valeur prédite exacte
print(f"Predicted value: {exact_prediction}")

# Arrondir pour faire correspondre aux catégories
rounded_prediction = round(exact_prediction)

# Convertir la prédiction en activité physique
activity_mapping = {0: "Walking", 1: "Jogging", 2: "Cycling"}
predicted_activity = activity_mapping.get(rounded_prediction, "Unknown")

# Afficher l'activité prédite
print(f"Predicted activity: {predicted_activity}")

Predicted value: 1.0
Predicted activity: Jogging

In [67]:
import pickle
import skl2onnx
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType

In [68]:
with open("act_phy.pickle","wb") as f : 
  pickle.dump(model3,f)

In [69]:
with open("act_phy.pickle","rb") as f : 
  model = pickle.load(f)

In [70]:
# Convertir en ONNX
#initial_type = [("float_input", FloatTensorType([None, X.shape[1]]))]
#onnx_model = convert_sklearn(model3, initial_types=initial_type)

# Sauvegarder en ONNX
#with open("model.onnx", "wb") as f:
    #f.write(onnx_model.SerializeToString())