In [242]:
#import the pandas library to read a CSV file
import pandas as pd
#import the numpy library to create a numpy array
import numpy as np

In [243]:
df = pd.read_csv('C:/Users/pc/Downloads/Oxygen Dataset Final.csv')

In [244]:
df

        age  gender  spo2     pr  c/nc  oxy_flow
0        27       0  74.0   72.0   1.0       6.0
1        53       1   NaN  110.0   NaN      28.0
2        56       0  99.0   98.0   1.0       NaN
3        26       1   NaN  110.0   1.0       4.0
4        52       0  69.0   84.0   1.0       0.0
...     ...     ...   ...    ...   ...       ...
199995   17       0  99.0    NaN   1.0      28.0
199996   48       1  99.0    NaN   1.0       5.0
199997   24       0  99.0  110.0   1.0      23.0
199998  100       1  99.0   95.0   1.0      25.0
199999   22       1  99.0   82.0   0.0      32.0

[200000 rows x 6 columns]

In [245]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 6 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   age       200000 non-null  int64
 1   gender    200000 non-null  int64
 2   spo2      173755 non-null  float64
 3   pr        167616 non-null  float64
 4   c/nc      173558 non-null  float64
 5   oxy_flow  162253 non-null  float64
dtypes: float64(4), int64(2)
memory usage: 9.2 MB

In [246]:
df.drop(['c/nc','oxy_flow'], axis =1, inplace=True)

In [247]:
df

        age  gender  spo2     pr
0        27       0  74.0   72.0
1        53       1   NaN  110.0
2        56       0  99.0   98.0
3        26       1   NaN  110.0
4        52       0  69.0   84.0
...     ...     ...   ...    ...
199995   17       0  99.0    NaN
199996   48       1  99.0    NaN
199997   24       0  99.0  110.0
199998  100       1  99.0   95.0
199999   22       1  99.0   82.0

[200000 rows x 4 columns]

In [248]:
df.isnull().sum()

age           0
gender        0
spo2      26245
pr        32384
dtype: int64

In [249]:
df.dropna(inplace=True)

In [250]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 144976 entries, 0 to 199999
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   age     144976 non-null  int64
 1   gender  144976 non-null  int64
 2   spo2    144976 non-null  float64
 3   pr      144976 non-null  float64
dtypes: float64(2), int64(2)
memory usage: 5.5 MB

In [251]:
df

        age  gender  spo2     pr
0        27       0  74.0   72.0
2        56       0  99.0   98.0
4        52       0  69.0   84.0
5        82       0  93.0   93.0
8        97       0  84.0  110.0
...     ...     ...   ...    ...
199993   76       0  99.0   95.0
199994   61       1  99.0  103.0
199997   24       0  99.0  110.0
199998  100       1  99.0   95.0
199999   22       1  99.0   82.0

[144976 rows x 4 columns]

In [252]:
df = df.rename(columns={'pr': 'heart_rate'})
df = df.rename(columns={'spo2': 'oxygen_rate'})

In [253]:
df

        age  gender  oxygen_rate  heart_rate
0        27       0         74.0        72.0
2        56       0         99.0        98.0
4        52       0         69.0        84.0
5        82       0         93.0        93.0
8        97       0         84.0       110.0
...     ...     ...          ...         ...
199993   76       0         99.0        95.0
199994   61       1         99.0       103.0
199997   24       0         99.0       110.0
199998  100       1         99.0        95.0
199999   22       1         99.0        82.0

[144976 rows x 4 columns]

In [254]:
def generate_target1(row):
    # 0: stable, 1: instable
    # Get the values from the row
    age = row['age']
    heart_rate = row['heart_rate']

    # Generate the target for heart rate
    if age <= 2 and 100 <= heart_rate <= 160:
        return 0
    elif 2 < age <= 6 and 70 <= heart_rate <= 120:
        return 0
    elif 6 < age <= 12 and 60 <= heart_rate <= 110:
        return 0
    elif 12 < age <= 18 and 50 <= heart_rate <= 100:
        return 0
    elif 18 < age and 60 <= heart_rate <= 100:
        return 0
    else:
        return 1

# Use the apply function to apply this function to each row in your DataFrame
# This will create a new Series with your target variable
df['heart_rate_stability'] = df.apply(generate_target1, axis=1)

# Now df includes your target variable
#df.to_csv('df_with_heart_rate_stability.csv', index=False)

In [255]:
df

        age  gender  oxygen_rate  heart_rate  heart_rate_stability
0        27       0         74.0        72.0                     0
2        56       0         99.0        98.0                     0
4        52       0         69.0        84.0                     0
5        82       0         93.0        93.0                     0
8        97       0         84.0       110.0                     1
...     ...     ...          ...         ...                   ...
199993   76       0         99.0        95.0                     0
199994   61       1         99.0       103.0                     1
199997   24       0         99.0       110.0                     1
199998  100       1         99.0        95.0                     0
199999   22       1         99.0        82.0                     0

[144976 rows x 5 columns]

In [256]:
def generate_target2(row):
    # 0: stable, 1: instable
    # Get the values from the row
    age = row['age']
    oxygen_rate = row['oxygen_rate']

    # Generate the target for oxygen rate
    if age <= 65 and 95 < oxygen_rate < 100:
        return 0
    elif 65 < age and 94 < oxygen_rate < 98:
        return 0
    else:
        return 1

# Use the apply function to apply this function to each row in your DataFrame
# This will create a new Series with your target variable
df['oxygen_rate_stability'] = df.apply(generate_target2, axis=1)

# Now df includes your target variable
#df.to_csv('df_with_oxygen_rate_stability.csv', index=False)

In [257]:
df

,age,gender,oxygen_rate,heart_rate,heart_rate_stability,oxygen_rate_stability
0,27,0,74.0,72.0,0,1
2,56,0,99.0,98.0,0,0
4,52,0,69.0,84.0,0,1
5,82,0,93.0,93.0,0,1
8,97,0,84.0,110.0,1,1
...,...,...,...,...,...,...
199993,76,0,99.0,95.0,0,1
199994,61,1,99.0,103.0,1,0
199997,24,0,99.0,110.0,1,0
199998,100,1,99.0,95.0,0,1
199999,22,1,99.0,82.0,0,0

In [258]:
def generate_target(row):
    # 0: stable, 1: instable, 2: grave
    # Get the values from the row
    oxygen_rate = row['oxygen_rate_stability']
    heart_rate = row['heart_rate_stability']

    # Generate the target
    if oxygen_rate == 0 and heart_rate == 0:
        return 0
    elif (oxygen_rate == 1 and heart_rate == 0) or (oxygen_rate == 0 and heart_rate == 1):
        return 1
    else:
        return 2

# Use the apply function to apply this function to each row in your DataFrame
# This will create a new Series with your target variable
df['stability'] = df.apply(generate_target, axis=1)

# Now df includes your target variable
df.to_csv('df_with_stability.csv', index=False)

In [259]:
df

,age,gender,oxygen_rate,heart_rate,heart_rate_stability,oxygen_rate_stability,stability
0,27,0,74.0,72.0,0,1,1
2,56,0,99.0,98.0,0,0,0
4,52,0,69.0,84.0,0,1,1
5,82,0,93.0,93.0,0,1,1
8,97,0,84.0,110.0,1,1,2
...,...,...,...,...,...,...,...
199993,76,0,99.0,95.0,0,1,1
199994,61,1,99.0,103.0,1,0,1
199997,24,0,99.0,110.0,1,0,1
199998,100,1,99.0,95.0,0,1,1
199999,22,1,99.0,82.0,0,0,0

In [260]:
df.describe()

,age,gender,oxygen_rate,heart_rate,heart_rate_stability,oxygen_rate_stability,stability
count,144976.000000,144976.000000,144976.000000,144976.000000,144976.000000,144976.000000,144976.000000
mean,45.968988,0.353817,88.071267,92.740536,0.435851,0.581910,1.017762
std,21.732860,0.478155,15.849728,15.958639,0.495870,0.493247,0.714162
min,17.000000,0.000000,35.000000,40.000000,0.000000,0.000000,0.000000
25%,28.000000,0.000000,83.000000,82.000000,0.000000,0.000000,1.000000
50%,43.000000,0.000000,96.000000,96.000000,0.000000,1.000000,1.000000
75%,61.000000,1.000000,99.000000,108.000000,1.000000,1.000000,2.000000
max,100.000000,1.000000,99.000000,110.000000,1.000000,1.000000,2.000000

In [261]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 144976 entries, 0 to 199999
Data columns (total 7 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   age                    144976 non-null  int64
 1   gender                 144976 non-null  int64
 2   oxygen_rate            144976 non-null  float64
 3   heart_rate             144976 non-null  float64
 4   heart_rate_stability   144976 non-null  int64
 5   oxygen_rate_stability  144976 non-null  int64
 6   stability              144976 non-null  int64
dtypes: float64(2), int64(5)
memory usage: 8.8 MB

In [262]:
df.isnull().sum()

age                      0
gender                   0
oxygen_rate              0
heart_rate               0
heart_rate_stability     0
oxygen_rate_stability    0
stability                0
dtype: int64

In [263]:
df.dropna(inplace=True)

In [264]:
df

,age,gender,oxygen_rate,heart_rate,heart_rate_stability,oxygen_rate_stability,stability
0,27,0,74.0,72.0,0,1,1
2,56,0,99.0,98.0,0,0,0
4,52,0,69.0,84.0,0,1,1
5,82,0,93.0,93.0,0,1,1
8,97,0,84.0,110.0,1,1,2
...,...,...,...,...,...,...,...
199993,76,0,99.0,95.0,0,1,1
199994,61,1,99.0,103.0,1,0,1
199997,24,0,99.0,110.0,1,0,1
199998,100,1,99.0,95.0,0,1,1
199999,22,1,99.0,82.0,0,0,0

In [265]:
X = df[['age', 'oxygen_rate','heart_rate']]
y = df['stability']

In [266]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [267]:
# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [268]:
# Normalize the features using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [269]:
# Convert the target to one-hot encoding
y_train = tf.keras.utils.to_categorical(y_train)
y_test = tf.keras.utils.to_categorical(y_test)

In [270]:
# Define the model
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')])

C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\dense.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [271]:
# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [272]:
# Train the model
model.fit(X_train, y_train, epochs=5, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/5
3625/3625 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.8881 - loss: 0.3076 - val_accuracy: 0.9571 - val_loss: 0.1185
Epoch 2/5
3625/3625 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.9614 - loss: 0.1071 - val_accuracy: 0.9750 - val_loss: 0.0731
Epoch 3/5
3625/3625 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.9777 - loss: 0.0647 - val_accuracy: 0.9840 - val_loss: 0.0469
Epoch 4/5
3625/3625 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.9859 - loss: 0.0441 - val_accuracy: 0.9855 - val_loss: 0.0386
Epoch 5/5
3625/3625 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.9895 - loss: 0.0319 - val_accuracy: 0.9915 - val_loss: 0.0281

In [273]:
def predict_patient_status(model, patient_data):
    # Assuming patient_data is a DataFrame containing one patient's data
    patient_data = scaler.transform(patient_data)  # Normalize the patient's data
    prediction = model.predict(patient_data)  # Make a prediction
    class_index = tf.argmax(prediction, axis=1).numpy()[0]  # Get the index of the predicted class

    # Define the class labels
    class_labels = ['stable', 'instable', 'grave']
    # Adjusted to fit 0: stable, 1: instable, 2: grave

    # Print the predicted class
    print(f"The patient is predicted to be: {class_labels[class_index]}")

In [274]:
df

,age,gender,oxygen_rate,heart_rate,heart_rate_stability,oxygen_rate_stability,stability
0,27,0,74.0,72.0,0,1,1
2,56,0,99.0,98.0,0,0,0
4,52,0,69.0,84.0,0,1,1
5,82,0,93.0,93.0,0,1,1
8,97,0,84.0,110.0,1,1,2
...,...,...,...,...,...,...,...
199993,76,0,99.0,95.0,0,1,1
199994,61,1,99.0,103.0,1,0,1
199997,24,0,99.0,110.0,1,0,1
199998,100,1,99.0,95.0,0,1,1
199999,22,1,99.0,82.0,0,0,0

In [275]:
df.describe()

,age,gender,oxygen_rate,heart_rate,heart_rate_stability,oxygen_rate_stability,stability
count,144976.000000,144976.000000,144976.000000,144976.000000,144976.000000,144976.000000,144976.000000
mean,45.968988,0.353817,88.071267,92.740536,0.435851,0.581910,1.017762
std,21.732860,0.478155,15.849728,15.958639,0.495870,0.493247,0.714162
min,17.000000,0.000000,35.000000,40.000000,0.000000,0.000000,0.000000
25%,28.000000,0.000000,83.000000,82.000000,0.000000,0.000000,1.000000
50%,43.000000,0.000000,96.000000,96.000000,0.000000,1.000000,1.000000
75%,61.000000,1.000000,99.000000,108.000000,1.000000,1.000000,2.000000
max,100.000000,1.000000,99.000000,110.000000,1.000000,1.000000,2.000000

In [276]:
df

,age,gender,oxygen_rate,heart_rate,heart_rate_stability,oxygen_rate_stability,stability
0,27,0,74.0,72.0,0,1,1
2,56,0,99.0,98.0,0,0,0
4,52,0,69.0,84.0,0,1,1
5,82,0,93.0,93.0,0,1,1
8,97,0,84.0,110.0,1,1,2
...,...,...,...,...,...,...,...
199993,76,0,99.0,95.0,0,1,1
199994,61,1,99.0,103.0,1,0,1
199997,24,0,99.0,110.0,1,0,1
199998,100,1,99.0,95.0,0,1,1
199999,22,1,99.0,82.0,0,0,0

In [277]:
# example1:
new_patient = pd.DataFrame([[97, 84.0, 110.0]], columns=['age', 'oxygen_rate', 'heart_rate'])
predict_patient_status(model, new_patient)

WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001BD2E4FB920> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001BD2E4FB920> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
The patient is predicted to be: grave

In [278]:
# example2:
new_patient = pd.DataFrame([[30, 98.0, 95.0]], columns=['age', 'oxygen_rate', 'heart_rate'])
predict_patient_status(model, new_patient)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
The patient is predicted to be: stable

In [279]:
# example3:
new_patient = pd.DataFrame([[61, 99.0, 103.0]], columns=['age', 'oxygen_rate', 'heart_rate'])
predict_patient_status(model, new_patient)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
The patient is predicted to be: instable

In [280]:
# Convert the model to TensorFlow Lite format
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

INFO:tensorflow:Assets written to: C:\Users\pc\AppData\Local\Temp\tmpxrd54tag\assets

INFO:tensorflow:Assets written to: C:\Users\pc\AppData\Local\Temp\tmpxrd54tag\assets

Saved artifact at 'C:\Users\pc\AppData\Local\Temp\tmpxrd54tag'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 3), dtype=tf.float32, name='keras_tensor_24')
Output Type:
  TensorSpec(shape=(None, 3), dtype=tf.float32, name=None)
Captures:
  1912120260368: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1912120259984: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1912120249424: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1912120261712: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1912120247696: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1912120260944: TensorSpec(shape=(), dtype=tf.resource, name=None)

In [281]:
# Save the TensorFlow Lite model to a file
with open('stability.tflite', 'wb') as f:
    f.write(tflite_model)